/* 
 * Fabulator API
 *
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DomainApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DomainApiTests
    {
        private DomainApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DomainApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DomainApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DomainApi
            //Assert.IsInstanceOfType(typeof(DomainApi), instance, "instance is a DomainApi");
        }

        
        /// <summary>
        /// Test DeleteDomainV1Id
        /// </summary>
        [Test]
        public void DeleteDomainV1IdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeleteDomainV1Id(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test GetDomainV1InfoId
        /// </summary>
        [Test]
        public void GetDomainV1InfoIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetDomainV1InfoId(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PatchDomainV1UpdateIdFieldValue
        /// </summary>
        [Test]
        public void PatchDomainV1UpdateIdFieldValueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string field = null;
            //string value = null;
            //var response = instance.PatchDomainV1UpdateIdFieldValue(id, field, value);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PostDomainV1Add
        /// </summary>
        [Test]
        public void PostDomainV1AddTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Model1 body = null;
            //var response = instance.PostDomainV1Add(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PostDomainV1QuerySkipLimit
        /// </summary>
        [Test]
        public void PostDomainV1QuerySkipLimitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //decimal? skip = null;
            //decimal? limit = null;
            //Model9 body = null;
            //var response = instance.PostDomainV1QuerySkipLimit(skip, limit, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PutDomainV1UpdateId
        /// </summary>
        [Test]
        public void PutDomainV1UpdateIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //Model1 body = null;
            //var response = instance.PutDomainV1UpdateId(id, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
