/* 
 * Fabulator API
 *
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExampleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ExampleApiTests
    {
        private ExampleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExampleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExampleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ExampleApi
            //Assert.IsInstanceOfType(typeof(ExampleApi), instance, "instance is a ExampleApi");
        }

        
        /// <summary>
        /// Test DeleteExampleV1IddomainId
        /// </summary>
        [Test]
        public void DeleteExampleV1IddomainIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iddomain = null;
            //string id = null;
            //var response = instance.DeleteExampleV1IddomainId(iddomain, id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test GetExampleV1InfoIddomainId
        /// </summary>
        [Test]
        public void GetExampleV1InfoIddomainIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iddomain = null;
            //string id = null;
            //var response = instance.GetExampleV1InfoIddomainId(iddomain, id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PatchExampleV1UpdateIddomainIdFieldValue
        /// </summary>
        [Test]
        public void PatchExampleV1UpdateIddomainIdFieldValueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iddomain = null;
            //string id = null;
            //string field = null;
            //string value = null;
            //var response = instance.PatchExampleV1UpdateIddomainIdFieldValue(iddomain, id, field, value);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PostExampleV1AddIddomain
        /// </summary>
        [Test]
        public void PostExampleV1AddIddomainTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iddomain = null;
            //Model4 body = null;
            //var response = instance.PostExampleV1AddIddomain(iddomain, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PostExampleV1QueryIddomainSkipLimit
        /// </summary>
        [Test]
        public void PostExampleV1QueryIddomainSkipLimitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iddomain = null;
            //decimal? skip = null;
            //decimal? limit = null;
            //Model9 body = null;
            //var response = instance.PostExampleV1QueryIddomainSkipLimit(iddomain, skip, limit, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PutExampleV1UpdateIddomainId
        /// </summary>
        [Test]
        public void PutExampleV1UpdateIddomainIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iddomain = null;
            //string id = null;
            //var response = instance.PutExampleV1UpdateIddomainId(iddomain, id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PutExampleV1UpdateJsonIddomainId
        /// </summary>
        [Test]
        public void PutExampleV1UpdateJsonIddomainIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string iddomain = null;
            //string id = null;
            //Model14 body = null;
            //var response = instance.PutExampleV1UpdateJsonIddomainId(iddomain, id, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
