/* 
 * Fabulator API
 *
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExecuteApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ExecuteApiTests
    {
        private ExecuteApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExecuteApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExecuteApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ExecuteApi
            //Assert.IsInstanceOfType(typeof(ExecuteApi), instance, "instance is a ExecuteApi");
        }

        
        /// <summary>
        /// Test PostExecuteV1LocalDomainKey
        /// </summary>
        [Test]
        public void PostExecuteV1LocalDomainKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string domain = null;
            //string key = null;
            //Model5 body = null;
            //var response = instance.PostExecuteV1LocalDomainKey(domain, key, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PostExecuteV1RuleIdrule
        /// </summary>
        [Test]
        public void PostExecuteV1RuleIdruleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idrule = null;
            //Model5 body = null;
            //var response = instance.PostExecuteV1RuleIdrule(idrule, body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test PostExecuteV1RuleIdruleExampleIdexample
        /// </summary>
        [Test]
        public void PostExecuteV1RuleIdruleExampleIdexampleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string idrule = null;
            //string idexample = null;
            //string idsentence = null;
            //var response = instance.PostExecuteV1RuleIdruleExampleIdexample(idrule, idexample, idsentence);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
