/* 
 * Fabulator API
 *
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Model14
    /// </summary>
    [DataContract]
    public partial class Model14 :  IEquatable<Model14>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Model14" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Model14() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Model14" /> class.
        /// </summary>
        /// <param name="json">json (required).</param>
        public Model14(Json json = default(Json))
        {
            // to ensure "json" is required (not null)
            if (json == null)
            {
                throw new InvalidDataException("json is a required property for Model14 and cannot be null");
            }
            else
            {
                this.Json = json;
            }
        }
        
        /// <summary>
        /// Gets or Sets Json
        /// </summary>
        [DataMember(Name="json", EmitDefaultValue=false)]
        public Json Json { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Model14 {\n");
            sb.Append("  Json: ").Append(Json).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Model14);
        }

        /// <summary>
        /// Returns true if Model14 instances are equal
        /// </summary>
        /// <param name="input">Instance of Model14 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Model14 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Json == input.Json ||
                    (this.Json != null &&
                    this.Json.Equals(input.Json))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Json != null)
                    hashCode = hashCode * 59 + this.Json.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
