/* 
 * Fabulator API
 *
 * Endpoint Fabulator project
 *
 * OpenAPI spec version: 1.0.0
 * Contact: torloneg@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Model12
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Model12Tests
    {
        // TODO uncomment below to declare an instance variable for Model12
        //private Model12 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Model12
            //instance = new Model12();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Model12
        /// </summary>
        [Test]
        public void Model12InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Model12
            //Assert.IsInstanceOfType<Model12> (instance, "variable 'instance' is a Model12");
        }


        /// <summary>
        /// Test the property 'Select'
        /// </summary>
        [Test]
        public void SelectTest()
        {
            // TODO unit test for the property 'Select'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Test]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

    }

}
